version: "3.8"
services:
  frontend:
    build: ./front-end
    container_name: app_frontend
    environment:
      API_URL: http://app_backend:3000
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: app_backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: rootpassword
      DB_NAME: angular
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: angular
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - sql_data:/var/lib/mysql

volumes:
  sql_data:
