apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: backend
  name: backend
spec:
  containers:
  - image: 192.168.1.150:5000/my-backend
    name: backend
    ports:
    - containerPort: 3000
    env:
    - name: DB_HOST
      value: "db"  
    - name: DB_USER
      value: "root"  
    - name: DB_PASS
      value: "rootpassword"  
    - name: DB_NAME
      value: "angular"  
    

