apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: frontend  
  name: frontend
spec:
  containers:
  - image: 192.168.1.150:5000/my-frontend:latest
    name: frontend
    ports:
    - containerPort: 80
    env:
    - name: API_URL
      value: "http://192.168.1.100:30008"  
  restartPolicy: Always
